project:
  type: website

website:
  title: "M10 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - href: about.qmd
        text: Essay on Shiny Apps
      - href: shiny-live.qmd
        text: Essay on Shinylive

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
